In [1]:
import json
import gzip
import pandas as pd

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_37568\840360880.py:3: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [46]:

# Importing metadata zip file and converting it to dataframe

def getDF(path):
  # Unzip the file, load in each line as an object
  g = gzip.open(path, 'rb')
  g = [json.loads(l) for l in g]

  # Map to a dictionary, then load in as a dataframe
  dict_df = {i: d for (i, d) in enumerate(g)}
  return pd.DataFrame.from_dict(dict_df, orient='index')

df = getDF('All_Beauty.json.gz')

In [6]:
# Identify all columns, their sizes and datatypes in json file 

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 371345 entries, 0 to 371344
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   overall         371345 non-null  float64
 1   verified        371345 non-null  bool
 2   reviewTime      371345 non-null  object
 3   reviewerID      371345 non-null  object
 4   asin            371345 non-null  object
 5   reviewerName    371307 non-null  object
 6   reviewText      370946 non-null  object
 7   summary         371139 non-null  object
 8   unixReviewTime  371345 non-null  int64
 9   vote            51899 non-null   object
 10  style           125958 non-null  object
 11  image           8391 non-null    object
dtypes: bool(1), float64(1), int64(1), object(9)
memory usage: 34.4+ MB

In [ ]:
# not null

In [17]:

# Selecting only the colums that are required for analysis

colums_reviewtext_asin = ["reviewText", "asin", "reviewerID"]
df = df[colums_reviewtext_asin]

df.describe()

       reviewText        asin      reviewerID
count      370946      371345          371345
unique     319643       32586          324038
top          Good  B000FOI48G  A2GJX2KCUSR0EI
freq          802        8672              27

In [43]:
df

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,vote,style,image
0,1.0,True,"02 19, 2015",A1V6B6TNIC10QE,0143026860,theodore j bigham,great,One Star,1424304000,NaN,NaN,NaN
1,4.0,True,"12 18, 2014",A2F5GHSXFQ0W6J,0143026860,Mary K. Byke,My husband wanted to reading about the Negro ...,... to reading about the Negro Baseball and th...,1418860800,NaN,NaN,NaN
2,4.0,True,"08 10, 2014",A1572GUYS7DGSR,0143026860,David G,"This book was very informative, covering all a...",Worth the Read,1407628800,NaN,NaN,NaN
3,5.0,True,"03 11, 2013",A1PSGLFK1NSVO,0143026860,TamB,I am already a baseball fan and knew a bit abo...,Good Read,1362960000,NaN,NaN,NaN
4,5.0,True,"12 25, 2011",A6IKXKZMTKGSC,0143026860,shoecanary,This was a good story of the Black leagues. I ...,"More than facts, a good story read!",1324771200,5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371340,1.0,True,"07 20, 2017",A202DCI7TV1022,B01HJEGTYK,Sam,It was awful. It was super frizzy and I tried ...,It was super frizzy and I tried to comb it and...,1500508800,NaN,NaN,NaN
371341,5.0,True,"03 16, 2017",A3FSOR5IJOFIBE,B01HJEGTYK,TYW,I was skeptical about buying this. Worried it...,Awesome,1489622400,34,NaN,NaN
371342,5.0,True,"03 1, 2017",A1B5DK6CTP2P24,B01HJEGTYK,Norma Jennings,Makes me look good fast.,Five Stars,1488326400,46,NaN,NaN
371343,2.0,True,"02 21, 2017",A23OUYS5IRMJS9,B01HJEGTYK,Lee,Way lighter than photo\nNot mix blend of color...,Ok but color way off and volume as well,1487635200,NaN,NaN,NaN
371344,2.0,True,"12 15, 2016",A24KQ9RVU81L87,B01HJEGTYK,Season341,No return instructions/phone # in packaging. ...,Might return for a replacement if I could.,1481760000,NaN,NaN,NaN

In [47]:
# Find if there are any reviews that are empty
df_empty_reviews_index = (df["reviewText"] == "" )|( df["reviewText"].isnull())
print("Rows that have empty reviews")

df[df_empty_reviews_index]

Rows that have empty reviews

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,vote,style,image
547,5.0,True,"03 4, 2017",A3TQJ5AQXW6CZH,1620213982,mona,NaN,Five Stars,1488585600,NaN,{'Size:': ' Color42'},NaN
3594,5.0,True,"05 21, 2015",A2CMCSBNYJETQY,1620213982,Bobby Hamrick,NaN,Part of a great combo,1432166400,NaN,{'Size:': ' 6.25 Inches'},[https://images-na.ssl-images-amazon.com/image...
4105,5.0,True,"01 7, 2015",A2W5DS4107108S,1620213982,Dimitry,NaN,Just a good idea!,1420588800,3,{'Size:': ' 6.25 Inches'},[https://images-na.ssl-images-amazon.com/image...
6361,5.0,True,"11 19, 2016",A2MZYX8PMNV32V,B000050FDY,Amani albadawi,NaN,Five Stars,1479513600,NaN,{'Size:': ' 2 Count'},NaN
6437,5.0,True,"03 20, 2016",ACEV4EGUYH56O,B000050FDY,Amazon Customer,NaN,Five Stars,1458432000,NaN,{'Size:': ' 2 Count'},NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
369099,5.0,True,"05 19, 2017",A16BQAEP3E5MAS,B01GOSELHE,Amazon Customer,NaN,Five Stars,1495152000,NaN,NaN,NaN
369260,3.0,True,"03 12, 2018",A1AXL15FT6ULO2,B01GQKM0AK,Jinhwa kim,NaN,Three Stars,1520812800,NaN,NaN,NaN
371092,5.0,True,"03 12, 2018",A461O3V81H0GY,B01HEVYINM,joe,NaN,Five Stars,1520812800,NaN,NaN,NaN
371213,4.0,True,"10 25, 2016",A2VYUF746IFMXJ,B01HHA8M8C,Amazon Customer,NaN,Four Stars,1477353600,NaN,NaN,[https://images-na.ssl-images-amazon.com/image...
371296,5.0,True,"06 7, 2017",A3T761GW3WVLED,B01HI75KNE,kasha,NaN,Good buy,1496793600,NaN,NaN,[https://images-na.ssl-images-amazon.com/image...

In [48]:
df = df.drop(df[ ( (df["reviewText"] == "" ) | ( df["reviewText"].isnull()) ) ].index)

df

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,vote,style,image
0,1.0,True,"02 19, 2015",A1V6B6TNIC10QE,0143026860,theodore j bigham,great,One Star,1424304000,NaN,NaN,NaN
1,4.0,True,"12 18, 2014",A2F5GHSXFQ0W6J,0143026860,Mary K. Byke,My husband wanted to reading about the Negro ...,... to reading about the Negro Baseball and th...,1418860800,NaN,NaN,NaN
2,4.0,True,"08 10, 2014",A1572GUYS7DGSR,0143026860,David G,"This book was very informative, covering all a...",Worth the Read,1407628800,NaN,NaN,NaN
3,5.0,True,"03 11, 2013",A1PSGLFK1NSVO,0143026860,TamB,I am already a baseball fan and knew a bit abo...,Good Read,1362960000,NaN,NaN,NaN
4,5.0,True,"12 25, 2011",A6IKXKZMTKGSC,0143026860,shoecanary,This was a good story of the Black leagues. I ...,"More than facts, a good story read!",1324771200,5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371340,1.0,True,"07 20, 2017",A202DCI7TV1022,B01HJEGTYK,Sam,It was awful. It was super frizzy and I tried ...,It was super frizzy and I tried to comb it and...,1500508800,NaN,NaN,NaN
371341,5.0,True,"03 16, 2017",A3FSOR5IJOFIBE,B01HJEGTYK,TYW,I was skeptical about buying this. Worried it...,Awesome,1489622400,34,NaN,NaN
371342,5.0,True,"03 1, 2017",A1B5DK6CTP2P24,B01HJEGTYK,Norma Jennings,Makes me look good fast.,Five Stars,1488326400,46,NaN,NaN
371343,2.0,True,"02 21, 2017",A23OUYS5IRMJS9,B01HJEGTYK,Lee,Way lighter than photo\nNot mix blend of color...,Ok but color way off and volume as well,1487635200,NaN,NaN,NaN
371344,2.0,True,"12 15, 2016",A24KQ9RVU81L87,B01HJEGTYK,Season341,No return instructions/phone # in packaging. ...,Might return for a replacement if I could.,1481760000,NaN,NaN,NaN

In [51]:
duplicate_list = ["reviewText", "asin", "reviewerID"]

duplicated_rows = df.duplicated(duplicate_list, keep = False)
df[duplicated_rows].sort_values(duplicate_list)

# Some reviews are the same but due to time deficiency of the project the reason for those duplicates wont be investigated

df = df.drop_duplicates(duplicate_list, keep = "last")
df

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,vote,style,image
0,1.0,True,"02 19, 2015",A1V6B6TNIC10QE,0143026860,theodore j bigham,great,One Star,1424304000,NaN,NaN,NaN
1,4.0,True,"12 18, 2014",A2F5GHSXFQ0W6J,0143026860,Mary K. Byke,My husband wanted to reading about the Negro ...,... to reading about the Negro Baseball and th...,1418860800,NaN,NaN,NaN
2,4.0,True,"08 10, 2014",A1572GUYS7DGSR,0143026860,David G,"This book was very informative, covering all a...",Worth the Read,1407628800,NaN,NaN,NaN
3,5.0,True,"03 11, 2013",A1PSGLFK1NSVO,0143026860,TamB,I am already a baseball fan and knew a bit abo...,Good Read,1362960000,NaN,NaN,NaN
4,5.0,True,"12 25, 2011",A6IKXKZMTKGSC,0143026860,shoecanary,This was a good story of the Black leagues. I ...,"More than facts, a good story read!",1324771200,5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371340,1.0,True,"07 20, 2017",A202DCI7TV1022,B01HJEGTYK,Sam,It was awful. It was super frizzy and I tried ...,It was super frizzy and I tried to comb it and...,1500508800,NaN,NaN,NaN
371341,5.0,True,"03 16, 2017",A3FSOR5IJOFIBE,B01HJEGTYK,TYW,I was skeptical about buying this. Worried it...,Awesome,1489622400,34,NaN,NaN
371342,5.0,True,"03 1, 2017",A1B5DK6CTP2P24,B01HJEGTYK,Norma Jennings,Makes me look good fast.,Five Stars,1488326400,46,NaN,NaN
371343,2.0,True,"02 21, 2017",A23OUYS5IRMJS9,B01HJEGTYK,Lee,Way lighter than photo\nNot mix blend of color...,Ok but color way off and volume as well,1487635200,NaN,NaN,NaN
371344,2.0,True,"12 15, 2016",A24KQ9RVU81L87,B01HJEGTYK,Season341,No return instructions/phone # in packaging. ...,Might return for a replacement if I could.,1481760000,NaN,NaN,NaN